use VMS;

CREATE TABLE CommitteeType(
CommitteeTypeID BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Name VARCHAR(100) NOT NULL
);

CREATE TABLE Country(
CountryID BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Name VARCHAR(100) NOT NULL,
abbreviation VARCHAR(5) NOT NULL
);

CREATE TABLE Region(
REgionID BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Name VARCHAR(100) NOT NULL,
CountryID BIGINT FOREIGN KEY References Country(CountryID)
ON DELETE SET NULL
ON UPDATE CASCADE
);

CREATE TABLE Committee(
CommitteeID BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Name VARCHAR(100) NOT NULL,
DateCreate Date DEFAULT(GETDATE()) NOT NULL,
CommitteeTypeID BIGINT FOREIGN KEY References CommitteeType (CommitteeTypeID)
ON DELETE SET NULL
ON UPDATE CASCADE
);

CREATE TABLE SubCommittee(
SubCommitteeID BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Name VARCHAR(100) NOT NULL,
DateCreate Date DEFAULT(GETDATE()) NOT NULL,
Active INT DEFAULT(1) NOT NULL
);

CREATE TABLE HajjSession(
HajjSessionID BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[Year] VARCHAR(100) NOT NULL,
DateStart Date  NOT NULL,
DateEnd Date  NOT NULL,
Active INT DEFAULT(1) NOT NULL
);


CREATE TABLE RegionCommittee(
RegionCommitteeID BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CommitteeID BIGINT FOREIGN KEY References Committee (CommitteeID) ON DELETE SET NULL ON UPDATE CASCADE,
SubCommitteeID BIGINT FOREIGN KEY References SubCommittee (SubCommitteeID) ON DELETE SET NULL ON UPDATE CASCADE,
HajjSessionID BIGINT FOREIGN KEY References HajjSession (HajjSessionID) ON DELETE SET NULL ON UPDATE CASCADE,
Active INT DEFAULT(1) NOT NULL
);


